// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batting.sql

package sqlc

import (
	"context"
)

const createBattingEntry = `-- name: CreateBattingEntry :exec
INSERT INTO batting(id, player_id, gamePk, at_bats, runs, hits, doubles, triples, home_runs, rbi, stolen_bases, caught_stealing, walks, strikeouts, hit_by_pitch, avg, obp, slugging, ops, left_on_base, sac_bunts, sac_flies) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
`

type CreateBattingEntryParams struct {
	PlayerID       int32
	Gamepk         int32
	AtBats         int32
	Runs           int32
	Hits           int32
	Doubles        int32
	Triples        int32
	HomeRuns       int32
	Rbi            int32
	StolenBases    int32
	CaughtStealing int32
	Walks          int32
	Strikeouts     int32
	HitByPitch     int32
	Avg            string
	Obp            string
	Slugging       string
	Ops            string
	LeftOnBase     int32
	SacBunts       int32
	SacFlies       int32
}

func (q *Queries) CreateBattingEntry(ctx context.Context, arg CreateBattingEntryParams) error {
	_, err := q.db.Exec(ctx, createBattingEntry,
		arg.PlayerID,
		arg.Gamepk,
		arg.AtBats,
		arg.Runs,
		arg.Hits,
		arg.Doubles,
		arg.Triples,
		arg.HomeRuns,
		arg.Rbi,
		arg.StolenBases,
		arg.CaughtStealing,
		arg.Walks,
		arg.Strikeouts,
		arg.HitByPitch,
		arg.Avg,
		arg.Obp,
		arg.Slugging,
		arg.Ops,
		arg.LeftOnBase,
		arg.SacBunts,
		arg.SacFlies,
	)
	return err
}

const resetBatting = `-- name: ResetBatting :exec
DELETE FROM batting
`

func (q *Queries) ResetBatting(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetBatting)
	return err
}
