// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: divisions.sql

package sqlc

import (
	"context"
)

const createDivision = `-- name: CreateDivision :exec
INSERT INTO Divisions (id, name) VALUES (
    $1,
    $2
)
`

type CreateDivisionParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreateDivision(ctx context.Context, arg CreateDivisionParams) error {
	_, err := q.db.Exec(ctx, createDivision, arg.ID, arg.Name)
	return err
}
