// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewGame = `-- name: CreateNewGame :exec
INSERT INTO games (gamePk, date_played, home_team_id, home_score, away_team_id, away_score) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateNewGameParams struct {
	Gamepk     int32
	DatePlayed pgtype.Date
	HomeTeamID int32
	HomeScore  int32
	AwayTeamID int32
	AwayScore  int32
}

func (q *Queries) CreateNewGame(ctx context.Context, arg CreateNewGameParams) error {
	_, err := q.db.Exec(ctx, createNewGame,
		arg.Gamepk,
		arg.DatePlayed,
		arg.HomeTeamID,
		arg.HomeScore,
		arg.AwayTeamID,
		arg.AwayScore,
	)
	return err
}

const getGameByGPK = `-- name: GetGameByGPK :one
SELECT gamepk, date_played, home_team_id, home_score, away_team_id, away_score FROM games WHERE gamepk = $1
`

func (q *Queries) GetGameByGPK(ctx context.Context, gamepk int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByGPK, gamepk)
	var i Game
	err := row.Scan(
		&i.Gamepk,
		&i.DatePlayed,
		&i.HomeTeamID,
		&i.HomeScore,
		&i.AwayTeamID,
		&i.AwayScore,
	)
	return i, err
}

const resetGames = `-- name: ResetGames :exec
DELETE FROM games
`

func (q *Queries) ResetGames(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetGames)
	return err
}
