// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: innings.sql

package sqlc

import (
	"context"
)

const createNewInning = `-- name: CreateNewInning :exec
INSERT INTO innings(id, gamePk, inning_name, home_runs, home_hits, home_errors, away_runs, away_hits, away_errors) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateNewInningParams struct {
	Gamepk     int32
	InningName string
	HomeRuns   int32
	HomeHits   int32
	HomeErrors int32
	AwayRuns   int32
	AwayHits   int32
	AwayErrors int32
}

func (q *Queries) CreateNewInning(ctx context.Context, arg CreateNewInningParams) error {
	_, err := q.db.Exec(ctx, createNewInning,
		arg.Gamepk,
		arg.InningName,
		arg.HomeRuns,
		arg.HomeHits,
		arg.HomeErrors,
		arg.AwayRuns,
		arg.AwayHits,
		arg.AwayErrors,
	)
	return err
}

const resetInnings = `-- name: ResetInnings :exec
DELETE FROM innings
`

func (q *Queries) ResetInnings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetInnings)
	return err
}
