// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Division struct {
	ID   int32
	Name string
}

type Record struct {
	ID          pgtype.UUID
	TeamID      int32
	Wins        int32
	Losses      int32
	Pct         string
	Streak      string
	RunsScored  int32
	RunsAgainst int32
	HomeWins    int32
	HomeLosses  int32
	AwayWins    int32
	AwayLosses  int32
}

type Team struct {
	ID           int32
	TeamName     string
	Abbreviation string
	DivisionID   int32
}
