// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Division struct {
	ID   int32
	Name string
}

type Game struct {
	Gamepk     int32
	DatePlayed pgtype.Date
	HomeTeamID int32
	HomeScore  int32
	AwayTeamID int32
	AwayScore  int32
}

type Inning struct {
	ID         pgtype.UUID
	Gamepk     int32
	InningName string
	HomeRuns   int32
	HomeHits   int32
	HomeErrors int32
	AwayRuns   int32
	AwayHits   int32
	AwayErrors int32
}

type Pitching struct {
	ID                 pgtype.UUID
	PlayerID           int32
	Gamepk             int32
	Era                string
	Whip               string
	InningsPitched     string
	Strikeouts         int32
	Walks              int32
	HomeRuns           int32
	EarnedRuns         int32
	Hits               int32
	Wins               int32
	Losses             int32
	GamesStarted       int32
	Saves              int32
	BlownSaves         int32
	StrikeoutsPer9     string
	WalksPer9          string
	StrikeoutWalkRatio string
}

type Player struct {
	ID              int32
	FirstName       string
	LastName        string
	Age             int32
	IsActive        bool
	TeamID          int32
	PrimaryPosition string
	Batside         string
	Pitchhand       string
}

type Record struct {
	ID          pgtype.UUID
	TeamID      int32
	Wins        int32
	Losses      int32
	Pct         string
	Streak      string
	RunsScored  int32
	RunsAgainst int32
	HomeWins    int32
	HomeLosses  int32
	AwayWins    int32
	AwayLosses  int32
}

type Team struct {
	ID           int32
	TeamName     string
	Abbreviation string
	DivisionID   int32
}
