// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pitching.sql

package sqlc

import (
	"context"
)

const createPitchingEntry = `-- name: CreatePitchingEntry :exec
INSERT INTO pitching (id, player_id, gamePk, era, whip, innings_pitched, strikeouts, walks, home_runs, earned_runs, hits, wins, losses, games_started, saves, blown_saves, strikeouts_per9, walks_per9, strikeout_walk_ratio) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
`

type CreatePitchingEntryParams struct {
	PlayerID           int32
	Gamepk             int32
	Era                string
	Whip               string
	InningsPitched     string
	Strikeouts         int32
	Walks              int32
	HomeRuns           int32
	EarnedRuns         int32
	Hits               int32
	Wins               int32
	Losses             int32
	GamesStarted       int32
	Saves              int32
	BlownSaves         int32
	StrikeoutsPer9     string
	WalksPer9          string
	StrikeoutWalkRatio string
}

func (q *Queries) CreatePitchingEntry(ctx context.Context, arg CreatePitchingEntryParams) error {
	_, err := q.db.Exec(ctx, createPitchingEntry,
		arg.PlayerID,
		arg.Gamepk,
		arg.Era,
		arg.Whip,
		arg.InningsPitched,
		arg.Strikeouts,
		arg.Walks,
		arg.HomeRuns,
		arg.EarnedRuns,
		arg.Hits,
		arg.Wins,
		arg.Losses,
		arg.GamesStarted,
		arg.Saves,
		arg.BlownSaves,
		arg.StrikeoutsPer9,
		arg.WalksPer9,
		arg.StrikeoutWalkRatio,
	)
	return err
}

const resetPitching = `-- name: ResetPitching :exec
DELETE FROM pitching
`

func (q *Queries) ResetPitching(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetPitching)
	return err
}
