// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package sqlc

import (
	"context"
)

const createNewPlayer = `-- name: CreateNewPlayer :exec
INSERT INTO players(id, first_name, last_name, age, is_active, team_id, primary_position, batside, pitchhand) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateNewPlayerParams struct {
	ID              int32
	FirstName       string
	LastName        string
	Age             int32
	IsActive        bool
	TeamID          int32
	PrimaryPosition string
	Batside         string
	Pitchhand       string
}

func (q *Queries) CreateNewPlayer(ctx context.Context, arg CreateNewPlayerParams) error {
	_, err := q.db.Exec(ctx, createNewPlayer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Age,
		arg.IsActive,
		arg.TeamID,
		arg.PrimaryPosition,
		arg.Batside,
		arg.Pitchhand,
	)
	return err
}

const resetPlayers = `-- name: ResetPlayers :exec
DELETE FROM players
`

func (q *Queries) ResetPlayers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetPlayers)
	return err
}
