// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package sqlc

import (
	"context"
)

const createTeamRecord = `-- name: CreateTeamRecord :exec
INSERT INTO records(id, team_id, wins, losses, pct, streak, runs_scored, runs_against, home_wins, home_losses, away_wins, away_losses) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateTeamRecordParams struct {
	TeamID      int32
	Wins        int32
	Losses      int32
	Pct         string
	Streak      string
	RunsScored  int32
	RunsAgainst int32
	HomeWins    int32
	HomeLosses  int32
	AwayWins    int32
	AwayLosses  int32
}

func (q *Queries) CreateTeamRecord(ctx context.Context, arg CreateTeamRecordParams) error {
	_, err := q.db.Exec(ctx, createTeamRecord,
		arg.TeamID,
		arg.Wins,
		arg.Losses,
		arg.Pct,
		arg.Streak,
		arg.RunsScored,
		arg.RunsAgainst,
		arg.HomeWins,
		arg.HomeLosses,
		arg.AwayWins,
		arg.AwayLosses,
	)
	return err
}

const resetRecords = `-- name: ResetRecords :exec
DELETE FROM records
`

func (q *Queries) ResetRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetRecords)
	return err
}
