// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams(id, team_name, abbreviation,division_id) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateTeamParams struct {
	ID           int32
	TeamName     string
	Abbreviation string
	DivisionID   int32
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam,
		arg.ID,
		arg.TeamName,
		arg.Abbreviation,
		arg.DivisionID,
	)
	return err
}

const resetTeams = `-- name: ResetTeams :exec
DELETE FROM teams
`

func (q *Queries) ResetTeams(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTeams)
	return err
}
